[PR] List Devices
tiennguyenhoan/xlr-kobiton-plugin pull request #3
Opened 2018-09-21 09:19 UTC by blackheat

2018-09-22 18:46 UTC, thangvo38 requested changes
Please take a look.

2018-09-22 18:46 UTC, thangvo38 commented on src/main/resources/kobiton/ListDevices.py
> +devices = []
The `devices` variable is a dictionary, not a list.
```
devices = {}
```
Please check and fix the below code

2018-09-22 18:46 UTC, thangvo38 commented on src/main/resources/kobiton/ListDevices.py
> +                print item['udid']
Remove this line.

2018-09-22 18:46 UTC, thangvo38 commented on src/main/resources/kobiton/ListDevices.py
> +def create_basic_authentication_token():
I think this function should be in another file.

2018-09-22 18:46 UTC, thangvo38 commented on src/main/resources/kobiton/ListDevices.py
> +def get_all_devices_list():
Same as above, but fix it to be used to call various api.

2018-09-22 18:46 UTC, thangvo38 commented on src/main/resources/kobiton/ListDevices.py
> +    devices_list = merge_devices(devices_list, isCloud, isPrivate, isFavorite)
Re-order the functions below to represent this call order.

2018-09-22 18:46 UTC, thangvo38 commented on src/main/resources/kobiton/ListDevices.py
> +def serialize_devices(devices_list=None):
Why does the default value is `None`? Is there any scenario where this parameter is `None`?

2018-09-22 18:46 UTC, thangvo38 commented on src/main/resources/kobiton/ListDevices.py
> +        devices_list = []
`return {}`

2018-09-26 08:06 UTC, tiennguyenhoan requested changes
As discussed, please make changes

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +kobiton_api_server = kobitonServer['url']
`api_server`

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +  'cloudDevices': cloudDevices,
```  'cloudDevices': isCloud,
  'privateDevices': isPrivate,
  'favoriteDevices': isFavorite```

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +def merge_list(group_options, devices_list=[]):
`merge_list ` -> `filter_devices`

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +def merge_list(group_options, devices_list=[]):
`def filter_devices(devices_list=[])`

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +    devices_list = merge_list(group_options, devices_list)
`devices_list` -> `formated_devices`

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +  for item in devices_list:
```  
for item in devices_list:
    if platform_options[item['platformName']]:
      filtered_list.append(item)
  return filtered_list
```

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +    print 'Failed to get devices list'
Print exception

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +    for name in devices_name:
using `Filter array`

2018-09-26 08:06 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +    for name in devices_name:
http://book.pythontips.com/en/latest/map_filter.html

2018-09-26 14:13 UTC, tiennguyenhoan requested changes
@blackheat please take a look!

2018-09-26 14:13 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +def create_basic_authentication_token():
@blackheat ?

2018-09-26 14:13 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +kobiton_api_server = kobitonServer['url']
@blackheat ?

2018-09-26 14:13 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +  except Exception as e:
`e` -> `err` or `error`

2018-09-26 14:13 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +    print e
```
print 'Failed to get devices list\n' + err
```

2018-09-26 14:13 UTC, NguyenHoanTien commented on src/main/resources/kobiton/ListDevices.py
> +  for option in group_options:
is it missing `if group_option[option]`

2018-09-26 14:13 UTC, NguyenHoanTien commented on src/main/resources/kobiton/ListDevices.py
> +  devices_name = model.split(',')
what happen with the case when user input only empty space ?

2018-09-26 14:13 UTC, NguyenHoanTien commented on src/main/resources/kobiton/ListDevices.py
> +    if re.search(name, device['deviceName'], re.IGNORECASE):
why do we need to use `re.search` functions ?

2018-09-26 14:13 UTC, NguyenHoanTien commented on src/main/resources/kobiton/ListDevices.py
> +      if device_matches_filter(device):
```if device_matches_filter(device) and classified_list.get(device['udid']) is None ```??

2018-09-27 08:01 UTC, tiennguyenhoan commented on gradle/wrapper/gradle-wrapper.properties
> +#Thu Sep 27 11:06:40 ICT 2018
Why do we need this comments ?

2018-09-27 08:01 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +
remove empty line

2018-09-27 08:01 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +
same

2018-09-27 08:01 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +  filtered_list = None
Why do you use none in here instead of this ```filtered_list = {}``` ?

2018-09-27 08:01 UTC, tiennguyenhoan commented on src/main/resources/kobiton/ListDevices.py
> +api_server = kobitonServer['url']
put comment here: 
**Below are just a suggestion**
```
 #Since the global variable filter already check the url condition, we don't need to checking url condition
api_server = kobitonServer['url']
```

2018-09-27 08:01 UTC, NguyenHoanTien commented on src/main/resources/synthetic.xml
> +    <property name="devices" label="Devices List" category="output" kind="map_string_string" description="List of available devices (Device Name, Platform Name, Device UDID)."/>
```
description="List of available devices (Device Name, Platform Name, Device UDID and device group)."
```

2018-09-27 08:06 UTC, tiennguyenhoan requested changes
@blackheat please take a look

2018-10-17 09:57 UTC, closed without merging